### ISSUE TITLE
Crash when saving after Great Britain formation

### ISSUE THREAD

**Issue by VincentPenelle** [Revok98/Paganism-Hegemony#2]
Hi, 
In my current playthrought (which caused a recent pull request I made), I encountered a recurrent problem: if Great Britain is formed by Brytenwalda, trying to save the game causes a crash.
The crash happens only if you try to save the game, there can be (in-game) months between Great Britain formation and the crash with no other symptoms.

I am attaching a file where this is going to happen (right before the formation of Great Britain) :
[paganism_hegemony_gbr_formation.eu4.zip](https://github.com/eympoin/Paganism-Hegemony/files/10608863/paganism_hegemony_gbr_formation.eu4.zip)

In this game, if you wait one month or two, Brytenwalda should form Great Britain. If you try to save a game after that, eu4 should crash.

Point of context: I am playing on Linux, in case that is useful. It could be possible that if you run on another platform the issue is not reproducible, in which case it could be way more difficult to detect.
Anyway, I would be happy to know whether it is reproducible or not, and where it might come from if you find it.
On my side, it also happened at other moments after Great Britain had formed, so I cheated a bit to dismantle partially Brytenwalda so it doesn't happen again.

Hope that helps.
Regards.

**Comment by eympoin** [comment]
Hi,
I was able to reproduce the bug on Windows so the problem doesn't lie here. i don't really know what is causing it. The only thing related in the error.log files were achievements (I deleted them to be sure but they weren't the cause of teh crash)
To be fair, going from Bretland to Great Britain shouldn't really be possible logically (Brytenwalda is juste the celtic version of Great Britain, the AI likely changed its primary culture in your playthrough). 
It seems that it fixed the problem.
Thanks a lot for the report ! Like I said in your pull request, if you have any suggestions/problems/fix/contributions please let me know.
best regards.

**Comment by VincentPenelle** [comment]
Hi,
Many thanks for your reactivity and your quick answers!
Indeed I was surprised to see Brytenwalda form Great Britain, that makes sense to prevent it to do it. And indeed, many other nations formed without issue, so it might be this particular transition which made some weird interaction.
I'm not completely sure in my game who formed Brytenwalda, but I think it was East Anglia (which would correspond to it being Angle and Germanic). Maybe that transition wasn't planned either?

Anyway, many thanks again for your reactivity and your work on that mod -- it is a very pleasant one.
If I see anything, I'll sure make you know here -- github is sure handy for that.
Best regards.

**Comment by eympoin** [comment]
It is indeed not planned either, thanks. I will also fix this.
Thank you again !
